export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const ADMIN_ROUTE = "/admin"
export const CART_ROUTE = "/cart"
export const ERROR_ROUTE = "/error"
export const HOME_ROUTE = "/"
export const CATALOG_ROUTE = "/catalog"
// export const PROFILE_ROUTE = "/profile"
// export const CATALOG_COLLECTIONS_ROUTE = `${CATALOG_ROUTE}#collections`
// export const CATALOG_FURNITURE_ROUTE = `${CATALOG_ROUTE}#furniture`
// export const CATALOG_LIGHTS_ROUTE = `${CATALOG_ROUTE}#lights`
// export const CATALOG_ACCESSORIES_ROUTE = `${CATALOG_ROUTE}#accessories`
// export const CATALOG_DELIVERY_ROUTE = `${CATALOG_ROUTE}#delivery`